// Generated by CoffeeScript 1.3.3
(function() {
  var DataOnWire,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  DataOnWire = (function() {

    DataOnWire.validOrigins = ["http://0.0.0.0:9294"];

    function DataOnWire() {
      this.sendMessage = __bind(this.sendMessage, this);

      this.requestXHR = __bind(this.requestXHR, this);

      this.receiveMessage = __bind(this.receiveMessage, this);
      window.addEventListener("message", this.receiveMessage, false);
    }

    DataOnWire.prototype.receiveMessage = function(e) {
      var reference;
      console.log("receiveMessage called from DataOnWire");
      reference = e.data.reference;
      return this.requestXHR(reference);
    };

    DataOnWire.prototype.requestXHR = function(reference) {
      var filter, url, _i, _len, _ref, _results,
        _this = this;
      console.log('requestXHR called from DataOnWire');
      _ref = ['u', 'g', 'r', 'i', 'z'];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        filter = _ref[_i];
        url = "http://ubret.s3.amazonaws.com/galaxyzoo3/lens/" + reference + "_" + filter + "_sci.fits";
        _results.push((function(url, reference) {
          var xhr;
          xhr = new XMLHttpRequest();
          xhr.open('GET', url);
          xhr.responseType = 'arraybuffer';
          xhr.onload = function(e) {
            var msg;
            msg = {
              origin: url,
              reference: reference,
              arraybuffer: e.currentTarget.response
            };
            return _this.sendMessage(msg);
          };
          return xhr.send();
        })(url, reference));
      }
      return _results;
    };

    DataOnWire.prototype.sendMessage = function(msg) {
      console.log('sendMessage called from DataOnWire');
      return window.parent.postMessage(msg, DataOnWire.validOrigins[0]);
    };

    return DataOnWire;

  })();

  this.DataOnWire = DataOnWire;

}).call(this);
